workflows:
  react-native-android:
    name: Build Android APK
    max_build_duration: 120
    environment:
      vars:
        PACKAGE_NAME: "com.brandzaffair" # Update this!
      node: 18.16.0
      java: 17
      android: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd android
          ./gradlew clean
      - name: Build release APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
